### PR TITLE
Fixed popular tags not working

### LINKED ISSUE #1116: Clicking on a "popular" tag does not add a filter by that tag
Clicking on a popular tag does not update the project listing to filter by that tag and the console shows a 404 after doing so. My guess is that this is due to the fact that the URL linked to for "popular" tags vs. selecting the tag manually through "Filter by tags" are different. 

The a href for python's "popular" tag is: 

> #/tags/python

The a href for python if clicked on in the "Filter by tags:" box is:

> #/filters/?tags=python

Proof of 404: 
404s

Demonstrations:
Nonfunctional "popular" (The first three projects do not include python but do not disappear)
popularstart

Functional "Filter by tags": (Projects that do not include python, like smallest dotnet, properly disappear) 

filterbytags

I'm new to making public contributions to GitHub (this is my first one!) and I'd love feedback on my contributions like this issue report, especially if it's critical as I'm trying to improve. Thanks for reading! Hoping to confirm this is an issue before I try experimenting with fixing it!

### PR DESCRIPTION
**Pull request by juliankrieger**
I fixed the popular tags not working by adding an on("click") eventHandler that changes the location.href according to the tag clicked. I'd be glad if it could be reviewed by either @ritwik12 or @Zarad1993 

Fixes #1116 in a clean and readable way.
~However, currently only one popular tag works at a time. I'll look into this this evening~

However, I'm not sure if it's enough to generate the correct link and change it accordingly, or if I should push the new tag to the projectServices "tags" array, too.

### CODE REVIEW

**Comment by juliankrieger** [comment]
I've tested it in my browser, multiple popular tags should now work

File: javascripts/main.js [hunk 1]
```diff
@@ -41,8 +41,30 @@
     }).val(labels).trigger('chosen:updated').change(function (e) {
       location.href = updateQueryStringParameter(getFilterUrl(), 'labels', encodeURIComponent(($(this).val() || "")));
     });
+
+    projectsPanel.find("ul.popular-tags").children().each(function(i, elem){
+        $(elem).on("click", function(){
+            let selTags = ($('.tags-filter').val() || [])
+            const selectedTag = preparePopTagName($(this).text() || "");
```
Comment (Zarad1993) [inline javascripts/main.js]: Hi @juliankrieger - This will fail on IE

testing-on-ie

File: javascripts/main.js [hunk 2]
```diff
@@ -41,8 +41,30 @@
     }).val(labels).trigger('chosen:updated').change(function (e) {
       location.href = updateQueryStringParameter(getFilterUrl(), 'labels', encodeURIComponent(($(this).val() || "")));
     });
+
+    projectsPanel.find("ul.popular-tags").children().each(function(i, elem){
+        $(elem).on("click", function(){
+            let selTags = ($('.tags-filter').val() || [])
```
Comment (Zarad1993) [inline javascripts/main.js]: This one too.

**Review by Zarad1993 — CHANGES_REQUESTED** [review]
This looks very neat, thank you!! Really small change where that will fail in IE. Please ignore my suggestion if we don't plan to support IE.

@ritwik12 @juliankrieger .

**Comment by juliankrieger** [comment]
I'm not sure if we plan to support IE, but thank you for testing it :) I will look into fixing the issues. I can't test for IE currently because wine isn't running correctly on arch at the moment

I removed the keywords now (I hope that's the issue, I really don't know a lot about IE11 and what it supports), can you test it again for me @Zarad1993 ? Thanks!

**Review by Zarad1993 — APPROVED** [review]
@juliankrieger - You can see in the doc of [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#Browser_compatibility) and [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility). They are supported on IE11. I can try testing this PR later tonight. Thank you

**Comment by juliankrieger** [comment]
I set up a personal gh pages site with git, so I can test IE compabillity now

**Comment by juliankrieger** [comment]
Seems to work in IE @ritwik12

**Comment by ritwik12** [comment]
@juliankrieger Cool, do check that it isn't harming any other functionality so that I wouldn't need to revert it later. Sorry I'm busy and will not be able to check on my local system. Code looks fine. Just review it on your local system if everything works fine.

**Comment by juliankrieger** [comment]
Doesnt cause any issues for me, but im going to write a few tests tonight if I can manage

**Comment by ritwik12** [comment]
@juliankrieger Cool

**Comment by ritwik12** [comment]
@juliankrieger Working. What made you delete CNAME? I have re added CNAME as site went down because of it.

**Comment by ritwik12** [comment]
@juliankrieger Thanks and appreciate your contributions!!

**Comment by juliankrieger** [comment]
@ritwik12 I didn't change this myself, I think the commit may have been autogenerated by "bundle exec", which I run before I run "jekyll serve" because I have only the most recent ruby on my arch linux machine. I'm sorry I didn't catch that earlier :/

@ritwik12 Are my content changes still merged though?

**Comment by ritwik12** [comment]
@juliankrieger That's fine, yes I've merged it and later added CNAME myself. Your commits are working properly.
